# -*- coding: utf-8 -*-
"""prgm7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YHUfVKP93E-xFG4auwkhK3Jfugv1gSFx
"""

import matplotlib.pyplot as plt

years = [2001, 2002, 2003, 2004, 2005, 2006, 2007]
car_values = [24000, 22500, 19700, 17500, 14500, 10000, 5800]

plt.figure(figsize=(10, 6))
plt.subplot(111)
plt.plot(years, car_values, linestyle='-', color='red', marker='*', markersize=20,

markerfacecolor='green')

plt.title(" \nMCA 2023-2025", loc="right")
plt.title("Value Depreciation", loc="left")
plt.xlabel("Year")
plt.ylabel("Car Value")

plt.show()