# -*- coding: utf-8 -*-
"""prgm5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15FrmXNmy0UVqe3QqUrFGJWsjk8EI4KEz
"""

import numpy as np

A = np.array([[2, 1, -2],[3, 0, 1],[1, 1, -1]])
b = np.array([-3, 5, -2])
x = np.linalg.solve(A, b)
print("Matrix A:")
print(A)

print("Vector b:")
print(b)

print("Solution for x:")
print(x)